// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.2
// source: example.proto

package xx

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// ExampleMessage1 - Example Leading Comment for ExampleMessage1
type ExampleMessage1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	F1  float64 `protobuf:"fixed64,1,opt,name=f1,proto3" json:"f1,omitempty"`
	F2  float32 `protobuf:"fixed32,2,opt,name=f2,proto3" json:"f2,omitempty"`
	F3  int32   `protobuf:"varint,3,opt,name=f3,proto3" json:"f3,omitempty"`
	F4  int64   `protobuf:"varint,4,opt,name=f4,proto3" json:"f4,omitempty"`
	F5  uint32  `protobuf:"varint,5,opt,name=f5,proto3" json:"f5,omitempty"`
	F6  uint64  `protobuf:"varint,6,opt,name=f6,proto3" json:"f6,omitempty"`
	F7  int32   `protobuf:"zigzag32,7,opt,name=f7,proto3" json:"f7,omitempty"`
	F8  int64   `protobuf:"zigzag64,8,opt,name=f8,proto3" json:"f8,omitempty"`
	F9  uint32  `protobuf:"fixed32,9,opt,name=f9,proto3" json:"f9,omitempty"`
	F10 uint64  `protobuf:"fixed64,10,opt,name=f10,proto3" json:"f10,omitempty"`
	F11 int32   `protobuf:"fixed32,11,opt,name=f11,proto3" json:"f11,omitempty"`
	F12 int64   `protobuf:"fixed64,12,opt,name=f12,proto3" json:"f12,omitempty"`
	F13 bool    `protobuf:"varint,13,opt,name=f13,proto3" json:"f13,omitempty"`
	F14 string  `protobuf:"bytes,14,opt,name=f14,proto3" json:"f14,omitempty"`
	F15 []byte  `protobuf:"bytes,15,opt,name=f15,proto3" json:"f15,omitempty"`
}

func (x *ExampleMessage1) Reset() {
	*x = ExampleMessage1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleMessage1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleMessage1) ProtoMessage() {}

func (x *ExampleMessage1) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleMessage1.ProtoReflect.Descriptor instead.
func (*ExampleMessage1) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleMessage1) GetF1() float64 {
	if x != nil {
		return x.F1
	}
	return 0
}

func (x *ExampleMessage1) GetF2() float32 {
	if x != nil {
		return x.F2
	}
	return 0
}

func (x *ExampleMessage1) GetF3() int32 {
	if x != nil {
		return x.F3
	}
	return 0
}

func (x *ExampleMessage1) GetF4() int64 {
	if x != nil {
		return x.F4
	}
	return 0
}

func (x *ExampleMessage1) GetF5() uint32 {
	if x != nil {
		return x.F5
	}
	return 0
}

func (x *ExampleMessage1) GetF6() uint64 {
	if x != nil {
		return x.F6
	}
	return 0
}

func (x *ExampleMessage1) GetF7() int32 {
	if x != nil {
		return x.F7
	}
	return 0
}

func (x *ExampleMessage1) GetF8() int64 {
	if x != nil {
		return x.F8
	}
	return 0
}

func (x *ExampleMessage1) GetF9() uint32 {
	if x != nil {
		return x.F9
	}
	return 0
}

func (x *ExampleMessage1) GetF10() uint64 {
	if x != nil {
		return x.F10
	}
	return 0
}

func (x *ExampleMessage1) GetF11() int32 {
	if x != nil {
		return x.F11
	}
	return 0
}

func (x *ExampleMessage1) GetF12() int64 {
	if x != nil {
		return x.F12
	}
	return 0
}

func (x *ExampleMessage1) GetF13() bool {
	if x != nil {
		return x.F13
	}
	return false
}

func (x *ExampleMessage1) GetF14() string {
	if x != nil {
		return x.F14
	}
	return ""
}

func (x *ExampleMessage1) GetF15() []byte {
	if x != nil {
		return x.F15
	}
	return nil
}

type ExampleMessage2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	F1  []float64 `protobuf:"fixed64,1,rep,packed,name=f1,proto3" json:"f1,omitempty"`
	F2  []float32 `protobuf:"fixed32,2,rep,packed,name=f2,proto3" json:"f2,omitempty"`
	F3  []int32   `protobuf:"varint,3,rep,packed,name=f3,proto3" json:"f3,omitempty"`
	F4  []int64   `protobuf:"varint,4,rep,packed,name=f4,proto3" json:"f4,omitempty"`
	F5  []uint32  `protobuf:"varint,5,rep,packed,name=f5,proto3" json:"f5,omitempty"`
	F6  []uint64  `protobuf:"varint,6,rep,packed,name=f6,proto3" json:"f6,omitempty"`
	F7  []int32   `protobuf:"zigzag32,7,rep,packed,name=f7,proto3" json:"f7,omitempty"`
	F8  []int64   `protobuf:"zigzag64,8,rep,packed,name=f8,proto3" json:"f8,omitempty"`
	F9  []uint32  `protobuf:"fixed32,9,rep,packed,name=f9,proto3" json:"f9,omitempty"`
	F10 []uint64  `protobuf:"fixed64,10,rep,packed,name=f10,proto3" json:"f10,omitempty"`
	F11 []int32   `protobuf:"fixed32,11,rep,packed,name=f11,proto3" json:"f11,omitempty"`
	F12 []int64   `protobuf:"fixed64,12,rep,packed,name=f12,proto3" json:"f12,omitempty"`
	F13 []bool    `protobuf:"varint,13,rep,packed,name=f13,proto3" json:"f13,omitempty"`
	F14 []string  `protobuf:"bytes,14,rep,name=f14,proto3" json:"f14,omitempty"`
	F15 [][]byte  `protobuf:"bytes,15,rep,name=f15,proto3" json:"f15,omitempty"`
}

func (x *ExampleMessage2) Reset() {
	*x = ExampleMessage2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleMessage2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleMessage2) ProtoMessage() {}

func (x *ExampleMessage2) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleMessage2.ProtoReflect.Descriptor instead.
func (*ExampleMessage2) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *ExampleMessage2) GetF1() []float64 {
	if x != nil {
		return x.F1
	}
	return nil
}

func (x *ExampleMessage2) GetF2() []float32 {
	if x != nil {
		return x.F2
	}
	return nil
}

func (x *ExampleMessage2) GetF3() []int32 {
	if x != nil {
		return x.F3
	}
	return nil
}

func (x *ExampleMessage2) GetF4() []int64 {
	if x != nil {
		return x.F4
	}
	return nil
}

func (x *ExampleMessage2) GetF5() []uint32 {
	if x != nil {
		return x.F5
	}
	return nil
}

func (x *ExampleMessage2) GetF6() []uint64 {
	if x != nil {
		return x.F6
	}
	return nil
}

func (x *ExampleMessage2) GetF7() []int32 {
	if x != nil {
		return x.F7
	}
	return nil
}

func (x *ExampleMessage2) GetF8() []int64 {
	if x != nil {
		return x.F8
	}
	return nil
}

func (x *ExampleMessage2) GetF9() []uint32 {
	if x != nil {
		return x.F9
	}
	return nil
}

func (x *ExampleMessage2) GetF10() []uint64 {
	if x != nil {
		return x.F10
	}
	return nil
}

func (x *ExampleMessage2) GetF11() []int32 {
	if x != nil {
		return x.F11
	}
	return nil
}

func (x *ExampleMessage2) GetF12() []int64 {
	if x != nil {
		return x.F12
	}
	return nil
}

func (x *ExampleMessage2) GetF13() []bool {
	if x != nil {
		return x.F13
	}
	return nil
}

func (x *ExampleMessage2) GetF14() []string {
	if x != nil {
		return x.F14
	}
	return nil
}

func (x *ExampleMessage2) GetF15() [][]byte {
	if x != nil {
		return x.F15
	}
	return nil
}

type ReturnType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnType) Reset() {
	*x = ReturnType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnType) ProtoMessage() {}

func (x *ReturnType) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnType.ProtoReflect.Descriptor instead.
func (*ReturnType) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{2}
}

var File_example_proto protoreflect.FileDescriptor

var file_example_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x76, 0x31, 0x22, 0x8d, 0x02, 0x0a, 0x0f, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x02, 0x66, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x02, 0x66, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x33, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x66, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x34, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x66, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x35, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x66, 0x35, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x36, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x66, 0x36, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x37, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x11, 0x52, 0x02, 0x66, 0x37, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x38, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x12, 0x52, 0x02, 0x66, 0x38, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x39, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x07, 0x52, 0x02, 0x66, 0x39, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x31, 0x30, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x03, 0x66, 0x31, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x31, 0x31,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x03, 0x66, 0x31, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x66,
	0x31, 0x32, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x10, 0x52, 0x03, 0x66, 0x31, 0x32, 0x12, 0x10, 0x0a,
	0x03, 0x66, 0x31, 0x33, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x66, 0x31, 0x33, 0x12,
	0x10, 0x0a, 0x03, 0x66, 0x31, 0x34, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x31,
	0x34, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x31, 0x35, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x66, 0x31, 0x35, 0x22, 0x8d, 0x02, 0x0a, 0x0f, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x31, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x02, 0x66, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x32, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x02, 0x52, 0x02, 0x66, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x33, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x02, 0x66, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x34, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x02, 0x66, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x35, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x02, 0x66, 0x35, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x36, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x02, 0x66, 0x36, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x37, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x11, 0x52, 0x02, 0x66, 0x37, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x38, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x12, 0x52, 0x02, 0x66, 0x38, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x39, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x07, 0x52, 0x02, 0x66, 0x39, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x31, 0x30, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x06, 0x52, 0x03, 0x66, 0x31, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x31, 0x31,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x0f, 0x52, 0x03, 0x66, 0x31, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x66,
	0x31, 0x32, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x10, 0x52, 0x03, 0x66, 0x31, 0x32, 0x12, 0x10, 0x0a,
	0x03, 0x66, 0x31, 0x33, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x08, 0x52, 0x03, 0x66, 0x31, 0x33, 0x12,
	0x10, 0x0a, 0x03, 0x66, 0x31, 0x34, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x66, 0x31,
	0x34, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x31, 0x35, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03,
	0x66, 0x31, 0x35, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x32, 0x79, 0x0a, 0x0e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x4e, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x1a, 0x0e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x08, 0x52, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x1a, 0x0e, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x00, 0x42, 0x42, 0x5a, 0x40,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x6e, 0x64, 0x6f,
	0x63, 0x75, 0x2d, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x2f, 0x61, 0x6c, 0x6c, 0x2d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x78, 0x78,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData = file_example_proto_rawDesc
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_proto_rawDescData)
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_proto_goTypes = []interface{}{
	(*ExampleMessage1)(nil), // 0: v1.ExampleMessage1
	(*ExampleMessage2)(nil), // 1: v1.ExampleMessage2
	(*ReturnType)(nil),      // 2: v1.ReturnType
}
var file_example_proto_depIdxs = []int32{
	0, // 0: v1.ExampleService.NonRepeated:input_type -> v1.ExampleMessage1
	1, // 1: v1.ExampleService.Repeated:input_type -> v1.ExampleMessage2
	2, // 2: v1.ExampleService.NonRepeated:output_type -> v1.ReturnType
	2, // 3: v1.ExampleService.Repeated:output_type -> v1.ReturnType
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleMessage1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleMessage2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_rawDesc = nil
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExampleServiceClient is the client API for ExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleServiceClient interface {
	NonRepeated(ctx context.Context, in *ExampleMessage1, opts ...grpc.CallOption) (*ReturnType, error)
	Repeated(ctx context.Context, in *ExampleMessage2, opts ...grpc.CallOption) (*ReturnType, error)
}

type exampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleServiceClient(cc grpc.ClientConnInterface) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) NonRepeated(ctx context.Context, in *ExampleMessage1, opts ...grpc.CallOption) (*ReturnType, error) {
	out := new(ReturnType)
	err := c.cc.Invoke(ctx, "/v1.ExampleService/NonRepeated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleServiceClient) Repeated(ctx context.Context, in *ExampleMessage2, opts ...grpc.CallOption) (*ReturnType, error) {
	out := new(ReturnType)
	err := c.cc.Invoke(ctx, "/v1.ExampleService/Repeated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceServer is the server API for ExampleService service.
type ExampleServiceServer interface {
	NonRepeated(context.Context, *ExampleMessage1) (*ReturnType, error)
	Repeated(context.Context, *ExampleMessage2) (*ReturnType, error)
}

// UnimplementedExampleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExampleServiceServer struct {
}

func (*UnimplementedExampleServiceServer) NonRepeated(context.Context, *ExampleMessage1) (*ReturnType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NonRepeated not implemented")
}
func (*UnimplementedExampleServiceServer) Repeated(context.Context, *ExampleMessage2) (*ReturnType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Repeated not implemented")
}

func RegisterExampleServiceServer(s *grpc.Server, srv ExampleServiceServer) {
	s.RegisterService(&_ExampleService_serviceDesc, srv)
}

func _ExampleService_NonRepeated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleMessage1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).NonRepeated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ExampleService/NonRepeated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).NonRepeated(ctx, req.(*ExampleMessage1))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleService_Repeated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleMessage2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).Repeated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ExampleService/Repeated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).Repeated(ctx, req.(*ExampleMessage2))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NonRepeated",
			Handler:    _ExampleService_NonRepeated_Handler,
		},
		{
			MethodName: "Repeated",
			Handler:    _ExampleService_Repeated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
